### ISSUE TITLE
Date/Time Settings and Timezone Impact on Credential Retrieval

### ISSUE THREAD

**Issue by gkatrakazas** [wwWallet/wallet-ecosystem#38]
When attempting to get credentials while presenting a valid ID, there is an issue where the process does not proceed as expected. This issue appears to be related to date/time settings and timezones not being correctly set or accurate within the system.

**Comment by kkmanos** [comment]
Resolved by wallet-enterprise [Clock tolerance PR](https://github.com/wwWallet/wallet-enterprise/pull/16)
